# Generated by Django 5.1.1 on 2024-09-04 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_area_cost_alter_client_area_job'),
        ('shots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.job'),
        ),
    ]
