# Generated by Django 5.1.1 on 2024-09-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0009_alter_shot_annotations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='shot_id',
            field=models.CharField(editable=False, max_length=36, unique=True),
        ),
    ]
