# Generated by Django 5.1.1 on 2024-09-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0010_alter_shot_shot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='shot_id',
            field=models.CharField(editable=False, max_length=24, unique=True),
        ),
    ]
