# Generated by Django 5.1.1 on 2024-09-23 12:23

import shots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0013_alter_shot_annotations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='annotations',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=shots.models.get_annotation_upload_path),
        ),
    ]
