# Generated by Django 5.1.1 on 2024-09-23 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0014_alter_shot_annotations'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='artists',
            field=models.ManyToManyField(related_name='shots', through='workspace.Workspace', to=settings.AUTH_USER_MODEL),
        ),
    ]
