# Generated by Django 5.1.1 on 2024-09-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0015_shot_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shot',
            name='artists',
        ),
    ]
