# Generated by Django 5.1.1 on 2024-09-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_area_alter_job_area'),
        ('shots', '0016_remove_shot_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.job'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shots.package'),
        ),
    ]
