# Generated by Django 5.1.1 on 2024-09-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0017_alter_shot_job_alter_shot_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='status',
            field=models.CharField(choices=[('#0', 'Bidding'), ('#1', 'Go'), ('#2', 'Hold'), ('#3', 'Working'), ('#4', 'Qc-ing'), ('#5', 'Done'), ('#6', 'Posted'), ('#7', 'Cancel')], default='pending', max_length=20),
        ),
    ]
