# Generated by Django 5.1.1 on 2024-10-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0022_alter_package_project_alter_project_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='earliest_delivery',
        ),
        migrations.RemoveField(
            model_name='package',
            name='latest_delivery',
        ),
    ]
