# Generated by Django 5.1.1 on 2024-10-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0024_rename_name_project_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='shot',
            name='shot_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
