# Generated by Django 5.1.1 on 2024-09-20 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.area'),
        ),
        migrations.AlterField(
            model_name='job',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clients.area'),
        ),
    ]
