# Generated by Django 5.1.1 on 2024-09-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_rename_avatar_user_avatar'),
        ('shots', '0014_alter_shot_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shots',
            field=models.ManyToManyField(blank=True, to='shots.shot'),
        ),
        migrations.AddField(
            model_name='user',
            name='shots_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/{username}/'),
        ),
    ]
