# Generated by Django 5.1.1 on 2024-09-23 12:50

import artists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_user_shots_user_shots_count_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=artists.models.get_avatar_upload_path),
        ),
    ]
