# Generated by Django 5.1.1 on 2024-09-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shots',
        ),
    ]
