# Generated by Django 5.1.1 on 2024-09-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_remove_user_shots'),
        ('shots', '0016_remove_shot_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shots',
            field=models.ManyToManyField(blank=True, to='shots.shot'),
        ),
    ]
